name: Build Example

on:
  workflow_dispatch:
  release:
    types: [published]
  # push:
  #   branches:
  #     - main
jobs:
  release:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      # - name: Setup NPM Latest
      #   run: npm i -g npm
      - name: Install Dependencies
        run: npm i
      - name: Test
        run: npm test
      - name: build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./example/public
          force_orphan: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
