name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npx npm@7.20.2 install
      - name: Test
        run: npm test
      - name: build
        run: npm run build
